### ISSUE TITLE
for SD: program Boss 1

### ISSUE THREAD

**Issue by inzeor** [Hexadoon/Data-Recovery#27]
Maggie - 5 hours

**Comment by inzeor** [comment]
- Locking camera when player gets to boss arena
- make big boss health bar across screen
- program different attacks for boss (shoot, rush, jump)

**Comment by SteelJackV2** [comment]
once you finish the boss object store that into the enemies folder to save it as a prefab

**Comment by mzhao3** [comment]
6/23: 7 hours (not done yet) 
What I did:
Locking camera when player gets to boss arena
make big boss health bar across screen
Shooting within a certain range
Rudimentary charge attack 
2 “stages”: once boss goes below 50%, faster shooting, additional movement speed

Want to add: 
rigid body colliders to prevent player from moving out of boss arena once fight starts
knock back on charge attack (or should it be instant death?) 
Enemy following player once they step into the arena
jumping mechanism
overall smoother enemy movement

**Comment by inzeor** [comment]
Maggie and Akash - 3 hours

- Get jump to work
- Fix probability of boss jumping, shooting, and charging
